### ISSUE TITLE
Make Debian2SPDX tool a standalone component

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/project-solda#11]
Original issue: https://git.ostc-eu.org/OSTC/planning/ip-compliance/-/issues/27

**Value**
Transform Debian2SPDX in a standalone tool will help other organization to use it

**Description**
Extract this part of Aliens4friends and make it a standalone tool that can be used separately

**Acceptance Criteria**
Use Debian2SPDX as a standalone component

**TODOS**
- [ ] Create manually a separate tool
- [ ] Invent a new command line interface to use the spdxdebian tool
- [ ] create a script or use another python installation method to create such a tool automatically (important to keep upstream source code updates in-sync with this tool)
