### ISSUE TITLE
EPIC: Implement a distributed knowledge base for packages and metadata - Project Solda

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/project-solda#21]
This EPIC is related to https://gitlab.eclipse.org/groups/eclipse/oniro-core/-/epics/93 in the Oniro project planning repository.
- [x] [Analysis of available technical solutions](https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/134)
- [x] [Design a PoC for distributed knowledge base](https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/135)
- [x] [Implementation of the first PoC](https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/136)
- [x] [Implementation of an API system to access packages and metadata information](https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/192)
- [x] [Integration of the distributed knowledge base in the IP toolchain](https://gitlab.eclipse.org/eclipse/oniro-core/oniro/-/issues/137)

**Comment by Piiit** [comment]
@LucaMiotto 

API = https://swagger.opendatahub.bz.it/?url=https://api.solda.testingmachine.eu
REPO = https://github.com/noi-techpark/solda-aliens4friends-api
