### ISSUE TITLE
EPIC: migrate code and infrastructure of IP compliance pipeline to Eclipse Foundation infrastructure

### ISSUE THREAD

**Issue by LucaMiotto** [noi-techpark/project-solda#23]
Source of truth for this activities: https://git.ostc-eu.org/oss-compliance/epics/-/issues/3

- [x] prepare a list of requirements for IT support for Eclipse Foundation (EF)
  See https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/README.md
- [x] work on documentation of various tools like debian matcher, new API and DB generation
  See https://git.ostc-eu.org/oss-compliance/toolchain/aliens4friends/-/merge_requests/64 

**UPDATE 2022-07-13**

Documentation updates and a new getting-started document for new contributors...

- [x] Remove the brainstorming part from the migration document and put it in a new document, link to it
   > https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/brainstorming.md
- [x] Create a new chapter: Maintenance
   > https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/README.md#maintenance
  - [x] Describe all external tools (curl, scancode, spdx java tool, etc.) that need update, that are considered to have a stable CLI interface, or that need additional coding and testing if upgraded to a new version (ex., yocto --> oniro responsibility, scancode, fossology)
  - [x] update of dashboard code, cont. deployment
  - [x] new mirrors + badges
  - [x] fossology backups, and eventual test installation to do updates in the future
  - [x] python updates?
  - [x] currently on debian 10, what if we upgrade?
  - [x] gitlab runner updates?
  - [x] docker or docker-compose udpates?
- [x] Create a little document for a new developer that takes over my solda duties
  > https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/getting-started-guide.md
  - [x] write a introduction of the project, what it is and why we do it like this
  - [x] link to all servers and services, describe how to access or whom to ask for access
  - [x] link to all gitlab, github repos
  - [x] link to the fossology instance
  - [x] explain tailscale a little
  - [x] ostc mattermost
  - [x] ef gitlab, who to ask
  - [x] link to existing videos, add warning about deprecation of some parts, but still useful as start
  - [x] link to all markdown documents and describe them a little in a bullet list

**UPDATE 2022-06-28**

Main documentation done, we need to wait for EF to make the next steps...

- [x] push code to the repository prepared for our project
- [ ] migrate Fossology machine
- [ ] migrate pipeline machine

**Comment by Piiit** [comment]
@LucaMiotto Done, see 
- https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/README.md
- https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/brainstorming.md
- https://git.ostc-eu.org/oss-compliance/wip/migration-plans/-/blob/main/getting-started-guide.md
